// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineSecureHospitalSystem.Data;

#nullable disable

namespace OnlineSecureHospitalSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250519191521_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("OnlineSecureHospitalSystem.Data.Models.Roles", b =>
                {
                    b.Property<int>("Role_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Role_ID");

                    b.ToTable("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
